spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksLibrary
    username: postgres
    password: nikola
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: validate
