#### GET ALL BOOKS
GET localhost:8080/api/v1/books

#### GET ALL BOOKS sorted Ascending by title
GET localhost:8080/api/v1/books?titleSort=ASC

#### GET ALL BOOKS sorted Descending by title
GET localhost:8080/api/v1/books?titleSort=DSC

#### GET BOOK filter by title
GET localhost:8080/api/v1/books?title=obCy

#### GET BOOK filter by author
GET localhost:8080/api/v1/books?author=albert Camus

#### GET BOOK filter by year
GET localhost:8080/api/v1/books?year=1925

#### GET BOOK filter by rate
GET localhost:8080/api/v1/books?rate=2


#### PATCH add new rate
PATCH localhost:8080/api/v1/books/062f817b-b423-4f01-aead-1546c948110a
Content-Type: application/json

{
  "rate": 2
}