#### GET ALL BOOKS
GET localhost:8080/api/v1/books

#### GET ALL BOOKS sorted Ascending by title
GET localhost:8080/api/v1/books?titleSort=ASC

#### GET ALL BOOKS sorted Descending by title
GET localhost:8080/api/v1/books?titleSort=DSC

#### GET BOOK filter by title
GET localhost:8080/api/v1/books?title=obCy